### ISSUE TITLE
How to loop until keypress?

### ISSUE THREAD

**Issue by lutzray** [pmbarrett314/curses-menu#17]
I'm trying to use an ExternalItem subclass where I do a non blocking menu.screen.getch() but the characters are being buffered until I press Enter.

I've even tried to start my own curses.wrapper(loop_until_keypress) inside curses-menu but it messes thing up...

Ah oui, merci pour le super module!

**Comment by pmbarrett314** [comment]
Just did a major refactor, closing some old issues. I did make some of the handling of things like this more robust, so something like this might work better now, but it's hard to test for every case like this.
