### ISSUE TITLE
Import Error: No module named '_curses' with Anaconda/Python3.5/Windows7 64bits

### ISSUE THREAD

**Issue by sevaader** [pmbarrett314/curses-menu#18]
Installed version 0.4.1 with pip install curses-menu

I just try to run the sample on the main code page.

```
Traceback (most recent call last):
  File "hci_cmd.py", line 1, in <module>
    from cursesmenu import *
  File "C:\Anaconda3\lib\site-packages\cursesmenu\__init__.py", line 1, in <module>
    from .curses_menu import CursesMenu
  File "C:\Anaconda3\lib\site-packages\cursesmenu\curses_menu.py", line 1, in <module>
    import curses
  File "C:\Anaconda3\lib\curses\__init__.py", line 13, in <module>
    from _curses import *
ImportError: No module named '_curses'
```

**Comment by sevaader** [comment]
pip uninstall curses-menu  and pip install  curses-menu make it works.

**Comment by pmbarrett314** [comment]
Python for Windows doesn't come with curses. You need to visit [http://www.lfd.uci.edu/~gohlke/pythonlibs/#curses](http://www.lfd.uci.edu/~gohlke/pythonlibs/#curses), download the version of curses that corresponds to your Windows and version of Python, and then pip install the whl file with the python you plan on using.

**Comment by jayeshBaviskar** [comment]
I Installed wheel "curses-2.2-cp36-cp36m-win_amd64" on python 3.6 on my windows 10 machine. but still, I am getting the same error. 

uninstalling and installing curses-menu also didn't work.

**Comment by roopeshukla** [comment]
go to ur python file check for the file name python36-32(**file name may be diff in ur case) and accordingly download the curses file. for ex in my case it is:curses-2.2-cp36-cp36m-win32.whl (**36-32 corresponds to the file name).your job is done. hope this will work for u.

**Comment by egabrum** [comment]
try `pip install windows-curses`

**Comment by meifu2027** [comment]
> try `pip install windows-curses`

easy and worked. thx

**Comment by Reveload** [comment]
> > try `pip install windows-curses`
> 
> Simple and effective. Thx :)

It does not work for me

**Comment by abdowiss** [comment]
pip install windows-curses

work for me thank's

**Comment by hpexeph** [comment]
> 
> 
> try `pip install windows-curses`

It worked for me either, Thanks

**Comment by xiang32** [comment]
> > > try `pip install windows-curses`
> > 
> > 
> > Simple and effective. Thx :)
> 
> It does not work for me

Maybe you should search it on pipy's website, look this: [https://pypi.org/project/windows-curses/#modal-close](url).

**Comment by Mouayedbelkhir** [comment]
> try `pip install windows-curses`

It does not work for me

**Comment by pwwang** [comment]
@Reveload @Mouayedbelkhir 

Have you tried `bpython-curses`, which worked for me, instead of `bpython`?

**Comment by Rajneesh-Tiwari** [comment]
pip install windows-curses works for me.
