### ISSUE TITLE
curses-menu and wxpython : wxWidget debug Alert

### ISSUE THREAD

**Issue by sevaader** [pmbarrett314/curses-menu#19]
I tried creating wxpython hci from cursesmenu. Both programs works one by one, but I have error using both at the same time.
I have an error on exit curses only (see attached error msg).

(I'm using Anaconda python27 on Windows 7 64bits).
![screen 27](https://cloud.githubusercontent.com/assets/5644310/14014214/7d48f7c6-f1b1-11e5-8191-64b189f57ca1.png)
Here the code.

```
import wx

from cursesmenu import *
from cursesmenu.items import *

class MainFrame(wx.Frame):
    def __init__(self, *args, **kwargs):
        wx.Frame.__init__(self, *args, **kwargs)
        self.CreateMenuBar()
        sizer = wx.BoxSizer(wx.VERTICAL)
        panel = wx.Panel(self)
        panel.SetSizer(sizer)
        sizer.Layout()

    def OnClose(self, evt):
        self.Destroy()
        evt.Skip()

    def CreateMenuBar(self):
        file_menu = wx.Menu()        
        AS_EXIT = wx.NewId()        
        file_menu.Append(AS_EXIT, "&Exit")
        self.Bind(wx.EVT_MENU, self.OnClose, id=AS_EXIT)


def start_hci():
    app = wx.PySimpleApp()
    f = MainFrame(parent=None, id=-1)
    f.Show()
    app.MainLoop()

if __name__ == "__main__":

    use_wx_with_curses = True  # combine wxpython and curses or not

    if use_wx_with_curses:        
        menu = CursesMenu("Version 0.1", "Debug HCI")
        menu.append_item(FunctionItem("Start HCI", start_hci))
        menu.show()
    else:
        start_hci()

```

**Comment by pmbarrett314** [comment]
This is indeed an issue. CursesMenu is currently multithreaded. I've got some ideas for reducing the number of threads, the way I do it now could use improvement, I may end up fixing this in the process. Here's a related thread. http://comments.gmane.org/gmane.comp.python.wxpython/101482

**Comment by pmbarrett314** [comment]
Closing some old issues, this one seems to be a combination of old python, old wx, and old curses-menu.
