### ISSUE TITLE
How to append SubmenuItem to a SelectionMenu

### ISSUE THREAD

**Issue by wblondel** [pmbarrett314/curses-menu#28]
Hi,

I have a list of options in a list.
Some of them have sub options.

Currently, I'm creating a SelectionMenu with only the options that don't have sub options (because SelectionMenu does not create submenus automatically).
I would like to append to this SelectionMenu the other options as submenus. How do I do that ? I did not find a way to append items to a SelectionMenu.

Thanks

**Comment by pmbarrett314** [comment]
This is over 5 years old, but I'm going to answer for posterity. The SelectionMenu class exists as a helper for a common use case: "I have a bunch of strings, I want the user to pick one and I want that selection back". This is a more complicated use case, you could get the same functionality by creating MenuItems in a loop and adding SubmenuItems as needed as well.

**Comment by wblondel** [comment]
Thank you for your answer. It's always worth commenting on old issues, who knows who might find them on search engines!

I don't remember what I ended up doing though 😄
