### ISSUE TITLE
how to get output from a function 

### ISSUE THREAD

**Issue by SimplySeth** [pmbarrett314/curses-menu#34]
I can see that there is a way to call a function with `FunctionItem`, but how I quite can't figure out how to get the output of the function I call.

**Comment by nickcounts** [comment]
@SimplySeth have you made any progress with this? I'm having trouble with FunctionItem calls as well. I'm not even totally sure my function callbacks (or whatever it's appropriate to call them) are executing 

cheers

**Comment by SimplySeth** [comment]
> @SimplySeth have you made any progress with this? I'm having trouble with FunctionItem calls as well. I'm not even totally sure my function callbacks (or whatever it's appropriate to call them) are executing
> 
> cheers

actually, I gave up. 
I was never able to figure it out.

**Comment by Flurrywinde** [comment]
I wondered the same thing. Put something like `input('Press Enter to continue')` at the end of the function, and then the output will stay around.
