### ISSUE TITLE
Support for vscode integrated terminal

### ISSUE THREAD

**Issue by Marko-L** [pmbarrett314/curses-menu#48]
It would be nice if this worked in vscode integrated terminal. I have tested on different integrated terminals for vscode on windows 10 be it cmd, powershell, bash and the like. Arrow keys do not respond. I am using python 39 which works fine for external terminals. Num keys respond but of course that only works if your menu list is below 10 elements. 10nth item on the menu and above I cannot select using num keys.

**Comment by pmbarrett314** [comment]
Looks related to [https://github.com/zephyrproject-rtos/windows-curses/issues/23](https://github.com/zephyrproject-rtos/windows-curses/issues/23). I'll add a workaround for the arrow keys.
