### ISSUE TITLE
0.7.0 or 0.7.1?

### ISSUE THREAD

**Issue by papoteur-mga** [pmbarrett314/curses-menu#61]
### Version

Other (include below)

### Operating System

Linux

### Environment

Mageia Linux

### What happened?

Pypi.org has 0.7.1 release, but there is no tags/release in this repo with this number.
Can you clarify?

**Comment by pmbarrett314** [comment]
Looks like a typo that I just missed. 0.7.0 on github is called 0.7.1 on pypi
