### ISSUE TITLE
Pylint alerts corrections as part of intervention experiment

### ISSUE THREAD

**Issue by evidencebp** [pmbarrett314/curses-menu#77]
**Is your feature request related to a problem? Please describe.**
There are two wildcard import in examples\issues\issue37.py

In general, wildcard imports should be avoided since the imported object are hidden.
Actually, a working code might break due to adding object to the imported file, that will conflict with others.

**Describe the solution you'd like**
Replace the wildcard imports with the specific objects to import.

**Additional context**

I'd like to conduct a software engineering experiment regarding the benefit of [Pylint](https://pypi.org/project/pylint/)  alerts removal.
The experiment is described [here](https://github.com/evidencebp/pylint-intervention/).
In the experiments, Pylint is used with some specific alerts, files are selected for intervention and control.
After the interventions are done, one can wait and examine the results.

I'm asking for your approval for conducting an intervention in your repository.

See examples of interventions in [stanford-oval/storm](https://github.com/stanford-oval/storm/pull/181), [gabfl/vault](https://github.com/gabfl/vault/pull/82), and [coreruleset/coreruleset](https://github.com/coreruleset/coreruleset/pull/3837).

In this project the intervention is very simple, fixing two wildcard import alerts.
Therefore I created the [PR](https://github.com/pmbarrett314/curses-menu/pull/76) already.

@pmbarrett314 , If you are OK with the PR I'll be very happy if you will merge it so I'll be able to observe the outcome of the fix.

**Comment by evidencebp** [comment]
@pmbarrett314, can you help me with the [PR](https://github.com/pmbarrett314/curses-menu/pull/76)?

In the first version, I made a mistake and it failed.
I fixed it but I cannot run again the test.
Code review is also needed and since the PR changes only two line, removing wildcard imports, I hope it will take a very short time.

**Comment by pmbarrett314** [comment]
closed by #76
